Encryption changes needed for NCS build system
nrfconnect/suit-generator pull request #160
Opened 2024-12-20 11:37 UTC by ahasztag

Ref: NCSDK-30935

2024-12-23 07:54 UTC, nordicjm requested changes

2024-12-23 07:54 UTC, nordicjm commented on ncs/Kconfig
> +	  This string is translated to the numeric KEY ID by the encryption script
help text is always at bottom

2024-12-23 07:54 UTC, nordicjm commented on ncs/Kconfig
> +	  Check the encryption script help for possible values
as above

2024-12-23 07:54 UTC, nordicjm commented on ncs/Kconfig
> +	default "sha-256"
this should be a choice, not a string

2024-12-27 10:47 UTC, ahasztag commented on ncs/Kconfig
> +	default "sha-256"
Fixed

2025-01-02 09:03 UTC, tomchy approved these changes

2025-01-03 09:35 UTC, NordicBuilder commented
pytest coverage results

<a href='https://jenkins-ncs.nordicsemi.no/job/latest/job/test-sdk-dfu/job/master/291/artifact/suit-generator/tests/coverage/index.html'>Detailed report</a>:
| Type | Coverage |
| --- | --- |
| lines | 89.8% (1900 of 2115 lines) |
| functions | 45.3% (168 of 371 functions) |
| branches | no data found |


*Note: This message is automatically posted and updated by the CI (latest/test-sdk-dfu/master/291)*

2025-01-03 12:17 UTC, adsz-nordic approved these changes

2025-01-07 07:20 UTC, nordicjm commented on ncs/Kconfig
> +
```suggestion
```

2025-01-07 07:20 UTC, nordicjm commented on ncs/Kconfig
> +	string "String name of the algorithm used to calculate the digest of the plaintext firmware"
```suggestion
	string
```
Should not have a prompt

2025-01-09 08:06 UTC, nordicjm approved these changes

2025-01-09 08:10 UTC, merged